name: Main Deploy

on:
  push:
    branches:
      - main
jobs:
  heroku-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
      - name: Add Heroku remote
        run: heroku git:remote -a $HEROKU_APP_NAME
        env:
          HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      - name: Unshallow if shallow clone
        run: git fetch --all --unshallow
      - name: Push to Heroku
        run: git push heroku main --force
      - name: Compile CSS and JavaScript
        run: |
          npm install
          npm run production
      - name: Copy .env
#         run: php -r "file_exists('.env') || copy('.env.example', '.env');"
        run: FILE=.env
            if [ -f "$FILE" ]; then
            echo "$FILE exists."
            fi
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
